# Generated by Django 5.2.1 on 2025-05-09 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='fecha_Fin',
            new_name='fecha_fin_asig',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_Inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
