# Generated by Django 5.2.1 on 2025-06-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_rename_fecha_fin_evento_fecha_fin_asig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
