# Generated by Django 5.2.1 on 2025-06-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='ID',
        ),
        migrations.AddField(
            model_name='evento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
