# Generated by Django 5.2.1 on 2025-06-10 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_remove_evento_id_evento_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo', models.IntegerField(choices=[(1, 'no puedo entrar'), (2, 'no me aparece el evento'), (3, 'otro')])),
                ('mensaje', models.TextField()),
                ('crweated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
